# Generated by Django 4.1.7 on 2023-03-05 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=30)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dish_type', models.CharField(choices=[('American', 'American'), ('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Mexican', 'Mexican'), ('Fast Food', 'Fastfood'), ('Thai', 'Thai'), ('Korean', 'Korean'), ('Dessert', 'Dessert')], default='American', max_length=30)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=30)),
                ('photo_1', models.ImageField(upload_to='')),
                ('photo_2', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
