# Generated by Django 4.1.7 on 2023-03-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_content',
            field=models.CharField(default='put oil', max_length=500),
            preserve_default=False,
        ),
    ]
